### ISSUE TITLE
Incorrectly serializes stuff like &nbsp;

### ISSUE THREAD

**Issue by matthewp** [canjs/can-simple-dom#19] opened 2015-12-04 16:25 UTC
`&nbsp;` becomes `&amp;nbsp;`, problem is here:

https://github.com/canjs/can-simple-dom/blob/master/lib/simple-dom/html-serializer.js#L29

**Comment by DesignByOnyx** [comment] 2016-01-02 05:30
Hey, I'm taking a look at this and I'm not sure the problem is on the serialization side but rather on the parsing side. Here's a test page to show how the browser treats things:

https://jsfiddle.net/ryanwheale/dgfbk8hc/

Observations:
- createTextNode, textContent, nodeValue all produce the same result.
- When a node's content is set with innerHTML - the textContent and nodeValue reflect the **unescaped value**. 
- When the node's content is retrieved with innerHTML, the value represents the escaped version of nodeValue. 

This means that our current method for serializing data is actually correct - escape all instances of `&<>`. If a nodeValue is equal to `"Foo &amp; Bar"` - the serialized version of that should be `Foo &amp;amp Bar`.

I am proposing that the fix for this issue go here - the `token.chars` should be unescaped before creating the text node:

https://github.com/canjs/can-simple-dom/blob/master/lib/simple-dom/html-parser.js#L37

This would match how the browser treats things. One [major] caveat to this technique is that _all_ html entities are unescaped. Take notice of the British Pound sign in the fiddle above (`&#x000A3;`). When using innerHTML, the entity is unescaped and is never re-escaped thereafter.

**Comment by DesignByOnyx** [comment] 2016-01-02 09:35
Here's an attempt at what I am proposing. This fixes the issue and has been tested on the Levi's project.

https://github.com/canjs/can-simple-dom/compare/master...canjs:19-unescape-entities?expand=1

**Comment by m-mujica** [comment] 2016-01-14 17:32
@DesignByOnyx have you tried this library before? https://github.com/mathiasbynens/he 

I was having some issues with encoded html entities in can-ssr, `he` seems pretty robust and it worked like a charm for me.

**Comment by justinbmeyer** [comment] 2016-11-10 01:55
@DesignByOnyx did this get fixed?

**Closed as completed** 2016-11-10 01:55 UTC
Labels: bug
